### ISSUE TITLE
Add edit capabilities to image template

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets#100]
threshold, elasticity, rotation, colors

**Comment by csbailey5t** [comment]
PR #113 Adds forms elements for threshold, elasticity, and rotation. For the moment, we're going to hold off on color and HOG features. I'll add a separate ticket for adding a 'delete' button for each template.

**Comment by csbailey5t** [comment]
Closing this since a big chunk of it is done and creating new, more specific tickets for the not done pieces.
