### ISSUE TITLE
Integrate histonets-cv (Python) into histonets (Ruby)

### ISSUE THREAD

**Issue by versae** [sul-cidr/histonets#12]
Probably using git submodules, Python pip, and the Ruby gem config

**Comment by mejackreed** [comment]
How riif does it: https://github.com/curationexperts/riiif/blob/master/app/models/riiif/file.rb#L65-L78

**Comment by mejackreed** [comment]
- [x] pip file
 - [x] documentation
 - [x] document diff versions of python (if needed)
 - [ ] basic class that invokes `histonets` with options (see riif implentation about)
