### ISSUE TITLE
After creating image templates, going back to create image templates page and advancing is raising a "Route not found" error that seems incorrect

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets#123]
@csbailey5t and I both experienced this problem. It appears to be happening on master

**Comment by mejackreed** [comment]
I think it only happens when we add a new template the second time

**Comment by csbailey5t** [comment]
Interestingly, in my local branch where I implement a delete action on the edit template view, a redirect to the create image template view works, allowing me to add a new template and get to the edit template view, as long as I have only created one image template. If I create two image templates, hit next through the first, then delete the second, after the redirect to the template creation view, if I create a new template and submit the form, I then hit the route error.
