### ISSUE TITLE
Determine what maps we can use as public fixtures

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets#17]
Since we have some copyright restrictions on the set of maps, are there any representative ones that we can use as fixtures as we develop the application?

**Comment by mejackreed** [comment]
cc @ashleyjester

**Comment by ashleyjester** [comment]
I talked to Stace and he thinks we could create a clip from one of Clayton's images and use that; clipping it would eliminate the copyright issues.  I also put a USGS map in the "sample data" folder in a new folder called "USGS maps" - here's a direct link: https://stanford.box.com/s/ipwppzc6d0oibr76ocjgggsuitfqvbno

I confirmed with Stace that all USGS maps are public domain so we can use them as is.
