### ISSUE TITLE
New image templates make previous ones be set to default values

### ISSUE THREAD

**Issue by versae** [sul-cidr/histonets#180]
When adding a new image template, settings for previously selected templates are set to default values

![histonets-create-template-issue-default-options](https://user-images.githubusercontent.com/173537/27549706-c72da210-5a51-11e7-8c72-fc121d906357.gif)

**Comment by mejackreed** [comment]
Err...

If they are saved then the threshold is persisted but not before saving ("Next Step")

**Comment by versae** [comment]
Any way to persist those locally first?

**Comment by mejackreed** [comment]
Possibly to push them back up to the parent component state

**Comment by csbailey5t** [comment]
As is probably expected, when one removes an image template, it rests the threshold on all other templates as well.
