### ISSUE TITLE
Setup image cropper

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets#33]

**Comment by mejackreed** [comment]
Also needs to be serialized on the rails side of things.

**Comment by aeschylus** [comment]
Javascript is added and working (osd and iiif-cropper), linked from the rails view in a page-specific manner.

What is needed now is to:
- [ ] add a method to the model to easily extract the region and image id information and restore previous settings.
- [ ] fill out the form with correctly-formatted region information when the user updates the region information with the cropper.

**Comment by mejackreed** [comment]
The team has been discussing this today in sprint planning. Having looked at iiif-cropper implementation, we are concerned that there isn't a way for an event to fire after the image is appropriately cropped. We think this is needed for the image-template implementation. @aeschylus do you have any insight on this?

**Comment by mejackreed** [comment]
- [ ] setup cropper component
 - [ ] cropper component should update region in form
 - [ ] form submission should use updated region
 - [ ] image clean page should use cropped image url to display the cropped area to be clean
