### ISSUE TITLE
Add radio button to image clean form for posterize

### ISSUE THREAD

**Issue by csbailey5t** [sul-cidr/histonets#68]
The form for posterize needs a radio button for selection the method for color reduction: kmeans or linear. Kmeans should be checked by default.

**Comment by mejackreed** [comment]
Great.. can we verify what the json for posterize should look like then?

**Comment by csbailey5t** [comment]
'[{"action":"posterize","options":{"colors":4, "method":"kmeans"}}]'

This worked for me by itself and with all the other actions in the json.

**Comment by mejackreed** [comment]
Great, and that color scale should be 0 -> 100?

**Comment by csbailey5t** [comment]
In the cli, it's an integer range from 2 to 128 due to algorithmic reasons. We could rescale if we need to.

**Comment by mejackreed** [comment]
ok. so that range should reflect that too I guess.

**Comment by mejackreed** [comment]
A prerequisite is a review and merge of https://github.com/sul-cidr/histonets/pull/70

**Comment by csbailey5t** [comment]
Per work this morning, the big question here is how to properly nest React components and share state as necessary.
