### ISSUE TITLE
Whenever an Image is created, preseed a field with the histogram

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets#82]
@versae can you specify what the format should be (and any imagemagick options?)

**Comment by mejackreed** [comment]
Potentially run in a background job

**Comment by versae** [comment]
We can use RMagick's [`color_histogram`](https://rmagick.github.io/image1.html#color_histogram) and store that in JSON in the model. A hash / dictionary with keys as RGB colors in a tuple and the absolute frequency of that colors as the value.

**Comment by mejackreed** [comment]
Closed with #117
