### ISSUE TITLE
Add a step between crop_image and image_clean that selects auto or manual clean

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets#89]
if autoclean, skip `:clean_image` step

**Comment by mejackreed** [comment]
Question for @versae / @csbailey5t ... Does the user need to modify any autoclean settings, or is this just a simple boolean?

**Comment by csbailey5t** [comment]
@mejackreed For the autoclean for now we are going to use `histonets enhance`, which just takes an input image and an output file. It doesn't take any values or options. 

@versae did build a different autocleaning command called `histonets clean`, which does take a number of options or values. If we switched to that later on, we would need to build a more complex form.
