### ISSUE TITLE
What data do we need to store for the image templates?

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/histonets#92]
I know there are some things like a mask, but what do we need to store here for each template? @versae @csbailey5t

**Comment by versae** [comment]
For now only the image (a IIIF URL would suffice), a threshold number (0 to 100), and a mask, which is a binary matrix of the same size of the template image, but optional. In the near future we might also need a boolean field for extracting HOG features, a threshold for rotation, and another threshold of elasticity, but I am still not sure how I am gonna make those work in a reasonable time.
